version: 2



build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    
python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py

  
  
formats:
  - pdf
  - epub
