version: 2

python:
  # Install our python package before building the docs
  version: 3.7
  requirements: docs/requirements.txt
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py

  
  
formats:
  - pdf
  - epub
