[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BIDSconvertR"
authors = [{name = "Wulms, Niklas", email = "wulms@uni-muenster.de"}]
dynamic = ["version", "description"]
